---
ip: "192.168.10.10"
memory: 2048
cpus: 1

folders:
    - map: ~/workspace/tripbuilder/
      to: /home/vagrant/workspace/tripbuilder

sites:
    - map: tripbuilder.app
      to: /home/vagrant/workspace/tripbuilder/public

variables:
    - key: APP_ENV
      value: local
